services:
  postgres:
    image: postgres:14
    container_name: thrift-seata-postgres
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  seata-server:
    image: seataio/seata-server:1.7.1
    platform: linux/amd64
    container_name: thrift-seata-server
    ports:
      - "8088:8088"
      - "7091:7091"
    environment:
      - STORE_MODE=file
      - SEATA_PORT=8088

volumes:
  postgres_data:
